In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#reads dataset using pandas function
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset
#shows the input dataset

      Age     Sex     BMI  Children Smoker      Charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
#Due to Nominal data present in dataset (i.e) State, Use get_dummies to split (One hot encoding)
#drop_first is used to eliminate 1st column of state as the result will be same even it is dropped and memory consuming is less
dataset = pd.get_dummies(dataset,dtype=int, drop_first = True)
#shows the input dataset
dataset

      Age     BMI  Children      Charges  Sex_male  Smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [5]:
dataset.columns
#for viewing all columns of dataset

Index(['Age', 'BMI', 'Children', 'Charges', 'Sex_male', 'Smoker_yes'], dtype='object')

In [6]:
indep=dataset[['Age', 'BMI', 'Children','Sex_male', 'Smoker_yes']]
dep=dataset['Charges']

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import AdaBoostRegressor
param_grid = {'loss': ['linear','square','exponential'],'n_estimators': [10,20,30]}
grid = GridSearchCV(AdaBoostRegressor(), param_grid, refit = True, verbose= 3,n_jobs=-1)

# fitting the model for grid search
grid.fit(indep, dep)

Fitting 5 folds for each of 9 candidates, totalling 45 fits

GridSearchCV(estimator=AdaBoostRegressor(), n_jobs=-1,
             param_grid={'loss': ['linear', 'square', 'exponential'],
                         'n_estimators': [10, 20, 30]},
             verbose=3)

In [11]:
# print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'loss': 'linear', 'n_estimators': 30}:

In [12]:
table=pd.DataFrame.from_dict(re)

In [13]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_loss,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.055573,0.018110,0.007983,0.008041,linear,10,"{'loss': 'linear', 'n_estimators': 10}",0.824254,0.776815,0.827069,0.819011,0.839504,0.817331,0.021348,2
1,0.041765,0.010598,0.003756,0.006561,linear,20,"{'loss': 'linear', 'n_estimators': 20}",0.842047,0.761836,0.821987,0.809250,0.849739,0.816972,0.031072,3
2,0.041185,0.018013,0.007321,0.008969,linear,30,"{'loss': 'linear', 'n_estimators': 30}",0.849852,0.785529,0.854285,0.800971,0.842494,0.826626,0.027941,1
3,0.043139,0.002541,0.003617,0.005178,square,10,"{'loss': 'square', 'n_estimators': 10}",0.685879,0.617185,0.667068,0.687990,0.665804,0.664785,0.025516,6
4,0.095528,0.013075,0.003588,0.006090,square,20,"{'loss': 'square', 'n_estimators': 20}",0.618741,0.530432,0.593258,0.569471,0.585560,0.579492,0.029238,8
5,0.130145,0.010418,0.008691,0.010579,square,30,"{'loss': 'square', 'n_estimators': 30}",0.560776,0.468407,0.532622,0.486670,0.544976,0.518690,0.035242,9
6,0.042395,0.008236,0.006781,0.008306,exponential,10,"{'loss': 'exponential', 'n_estimators': 10}",0.803191,0.752167,0.797275,0.783513,0.823136,0.791856,0.023584,4
7,0.087915,0.009933,0.012338,0.010847,exponential,20,"{'loss': 'exponential', 'n_estimators': 20}",0.719655,0.674955,0.734901,0.732693,0.732007,0.718842,0.022582,5
8,0.140248,0.012949,0.006623,0.005999,exponential,30,"{'loss': 'exponential', 'n_estimators': 30}",0.687208,0.608650,0.650475,0.680899,0.690588,0.663564,0.030909,7

In [14]:
Age_input=float(input("Age:"))
BMI_input=float(input("BMI:"))
Children_input=float(input("Children:"))
Sex_male_input=int(input("Sex Male 0 or 1:"))
Smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 20
BMI: 20
Children: 2
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 1

In [15]:
Future_Prediction=grid.predict([[Age_input,BMI_input,Children_input,Sex_male_input,Smoker_yes_input]])
#change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[18755.35660015]

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but AdaBoostRegressor was fitted with feature names
  warnings.warn(